version: 0.2
env:
  variables:
    S3_OUTPUT: "s3://zclabs.io"
phases:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build
  post_build:
    commands:
      - aws s3 cp --recursive --acl public-read ./build s3://zclabs.io/
      - aws s3 cp --acl public-read --cache-control="max-age=0, no-cache, no-store, must-revalidate" ./build/index.html s3://zclabs.io/
      - aws cloudfront create-invalidation --distribution-id ELAMEW7LMSWGP --paths "*"
artifacts:
  files:
    - "**/*"
  base-directory: "build"
  discard-paths: no
