version: 0.2
env:
  variables:
    S3_OUTPUT: "s3://zclabs.io"
phases:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build
  post_build:
    commands:
      - aws s3 rm s3://zclabs.io --recursive
      - aws s3 cp --recursive ./ s3://zclabs.io --recursive --exclude "node_modules" --acl public-read
artifacts:
  files:
    - "build/**/*"
  base-directory: "/"
  discard-paths: no
